### ISSUE TITLE
Get a NoClassDefFoundError Exception

### ISSUE THREAD

**Issue by Ruil** [oaqa/solr-provider#3]
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/hash/Hashing
    at edu.cmu.lti.oaqa.ecd.phase.Trace.<clinit>(Trace.java:24)
    at edu.cmu.lti.oaqa.ecd.phase.ProcessingStepUtils.getTraceString(ProcessingStepUtils.java:59)
    at edu.cmu.lti.oaqa.ecd.phase.ProcessingStepUtils.getTrace(ProcessingStepUtils.java:51)
    at edu.cmu.lti.oaqa.ecd.flow.FixedFlowController797182$FixedFlowObject.getTraceString(FixedFlowController797182.java:205)
    at edu.cmu.lti.oaqa.ecd.flow.FixedFlowController797182$FixedFlowObject.next(FixedFlowController797182.java:249)
    at org.apache.uima.analysis_engine.asb.impl.FlowContainer.next(FlowContainer.java:100)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:546)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:409)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:342)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:267)
    at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
    at edu.cmu.lti.oaqa.ecd.driver.SimplePipelineRev803.runPipeline(SimplePipelineRev803.java:244)
    at edu.cmu.lti.oaqa.ecd.driver.SimplePipelineRev803.runPipeline(SimplePipelineRev803.java:154)
    at edu.cmu.lti.oaqa.ecd.driver.ECDDriver.run(ECDDriver.java:66)
    at edu.cmu.lti.oaqa.ecd.driver.ECDDriver.main(ECDDriver.java:93)
Caused by: java.lang.ClassNotFoundException: com.google.common.hash.Hashing
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 15 more

**Comment by elmer-garduno** [comment]
This part of the problem seems to be the same that we had in the morning (the google guava version).

What do you have on the `<dependencies>` tag on your maven file?

Could you run the maven task with the Debug option enabled (Run as configurations) and attach the output here?
